version: 2

models:
  - name: products_sale
    description: Coffee shop customer orders
    columns:
      - name: order_id
        description: Unique order identifier
        tests:
          - not_null
          - unique